# Demo
Group 24: Jessica A Wijaya, Shujian Zhu, Malik Wagih, William Palmer

# 3. Installation
Th package uses a setup.py file for a simple installation, you need to to run the following command in the package main folder:

```
pip install .
```

# 4. How to Use AutoDiff 
In this section, we demo the the AutoDiff package and its capabilities:

In [1]:
import AutoDiff as ad
import numpy as np

The AutoDiff package can be used in two different ways:

### 4.1. Create an AD_Object()
Alternatively, you can delcare an AD_Object(value, label) and use it as a variable; the AD object will store the value and derivative with each subsequent elementary operation.  

#### 4.1.1 Single Variables

In [2]:
x = ad.AD_Object(2, 'x')
y = -x**3 + 2*x**2 + 3*x + 5
print("val: ", y.val,"\nder: ", y.der)
print(y)
print(y.derivative('x'))

val:  11 
der:  {'x': -1}
AD Object: Value = 11.000, Derivative: d(x)= -1.000 ; 
-1


In [3]:
x = ad.AD_Object(2, 'x')
y = (-2* x**2) /x
print("val: ", y.val,"\nder: ", y.der)
print(y)
print(y.derivative('x'))

val:  -4.0 
der:  {'x': -2.0}
AD Object: Value = -4.000, Derivative: d(x)= -2.000 ; 
-2.0


In [4]:
w = ad.AD_Object(2, 'w')
z = -w**3 + 2*w**2 + 3*w + 5
print("val: ", z.val,"\nder: ", z.der)
print(z)
print(z.derivative('w'))

val:  11 
der:  {'w': -1}
AD Object: Value = 11.000, Derivative: d(w)= -1.000 ; 
-1


In [5]:
## Elementary function example  
x = ad.AD_Object(0, 'x')
y = ad.cos(x)
print(y)
print(y.derivative('x'))

AD Object: Value = 1.000, Derivative: d(x)= -0.000 ; 
-0.0


#### 4.1.2 Multiple Variables

In [6]:
x = ad.AD_Object(2, 'x')
y = ad.AD_Object(3, 'y')

f = 2*x**2 + y

print("val: ", f.val,"\nder: ", f.der)
print("f'(x) = ", f.der['x'])
print(f)
print(f.derivative('x'))
print(f.derivative('y'))

val:  11 
der:  {'x': 8, 'y': 1}
f'(x) =  8
AD Object: Value = 11.000, Derivative: d(x)= 8.000 ; d(y)= 1.000 ; 
8
1


In [7]:
x = ad.AD_Object(2, 'x')
y = ad.AD_Object(3, 'y')

f = 2*x**2 + 2*y**2

print("val: ", f.val,"\nder: ", f.der)
print(f)
print(f.derivative('x'))

val:  26 
der:  {'x': 8, 'y': 12}
AD Object: Value = 26.000, Derivative: d(x)= 8.000 ; d(y)= 12.000 ; 
8


In [8]:
x = ad.AD_Object(2, 'x')
y = ad.AD_Object(3, 'y')

f = 2*(x**2)*y 

print("val: ", f.val,"\nder: ", f.der)
print(f)
print(f.derivative('x'))

val:  24 
der:  {'x': 24, 'y': 8}
AD Object: Value = 24.000, Derivative: d(x)= 24.000 ; d(y)= 8.000 ; 
24


In [9]:
x = ad.AD_Object(2, 'x')
y = ad.AD_Object(4, 'y')

f = (2*(x**2))/y 

print("val: ", f.val,"\nder: ", f.der)
print(f)
print(f.derivative('x'))

val:  2.0 
der:  {'x': 2.0, 'y': -0.5}
AD Object: Value = 2.000, Derivative: d(x)= 2.000 ; d(y)= -0.500 ; 
2.0


### 4.2 Using string function as input

#### 4.2.1 Single Variables

In [10]:
y = ad.AD_eval("-x**3 + 2*x**2 + 3*x + 5", "x", 2)
print("val: ", y.val,"\nder: ", y.der)
print(y)
print(y.derivative('x'))

val:  11 
der:  {'x': -1}
AD Object: Value = 11.000, Derivative: d(x)= -1.000 ; 
-1


#### 4.2.2 Multiple Variables

In [11]:
f = ad.AD_eval("2*x**2 + 2*y**2", ['x', 'y'], [2, 3])

print("val: ", f.val,"\nder: ", f.der)
print(f)
print(f.derivative('x'))

val:  26 
der:  {'x': 8, 'y': 12}
AD Object: Value = 26.000, Derivative: d(x)= 8.000 ; d(y)= 12.000 ; 
8


## 4.3. Vectorized input

Vector manipulation is easy to handle using AD_Vector to intitalize a vector of AD_Objects that can be used as numpy arrays.  

In [12]:
x = ad.AD_Vector(np.arange(1,10), label='x')

z = x**2

print(z)

print(ad.value(z))
print(ad.derivative(z, 'x'))

[AD Object: Value = 1.000, Derivative: d(x)= 2.000 ;
 AD Object: Value = 4.000, Derivative: d(x)= 4.000 ;
 AD Object: Value = 9.000, Derivative: d(x)= 6.000 ;
 AD Object: Value = 16.000, Derivative: d(x)= 8.000 ;
 AD Object: Value = 25.000, Derivative: d(x)= 10.000 ;
 AD Object: Value = 36.000, Derivative: d(x)= 12.000 ;
 AD Object: Value = 49.000, Derivative: d(x)= 14.000 ;
 AD Object: Value = 64.000, Derivative: d(x)= 16.000 ;
 AD Object: Value = 81.000, Derivative: d(x)= 18.000 ; ]
[ 1.  4.  9. 16. 25. 36. 49. 64. 81.]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [13]:
x = ad.AD_Vector(np.arange(1,10), label='x')

z = np.sin(x)

print(z)

print(ad.value(z))
print(ad.derivative(z, 'x'))

[AD Object: Value = 0.841, Derivative: d(x)= 0.540 ;
 AD Object: Value = 0.909, Derivative: d(x)= -0.416 ;
 AD Object: Value = 0.141, Derivative: d(x)= -0.990 ;
 AD Object: Value = -0.757, Derivative: d(x)= -0.654 ;
 AD Object: Value = -0.959, Derivative: d(x)= 0.284 ;
 AD Object: Value = -0.279, Derivative: d(x)= 0.960 ;
 AD Object: Value = 0.657, Derivative: d(x)= 0.754 ;
 AD Object: Value = 0.989, Derivative: d(x)= -0.146 ;
 AD Object: Value = 0.412, Derivative: d(x)= -0.911 ; ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]


In [14]:
x = ad.AD_Vector(np.arange(1,10), label='x') 
y = ad.AD_Vector(np.arange(1,10), label='y')
z = 2*x**2 + y**2

print(z)

print(ad.value(z))
print(ad.derivative(z, 'x'))
print(ad.derivative(z, 'y'))

[AD Object: Value = 3.000, Derivative: d(x)= 4.000 ; d(y)= 2.000 ;
 AD Object: Value = 12.000, Derivative: d(x)= 8.000 ; d(y)= 4.000 ;
 AD Object: Value = 27.000, Derivative: d(x)= 12.000 ; d(y)= 6.000 ;
 AD Object: Value = 48.000, Derivative: d(x)= 16.000 ; d(y)= 8.000 ;
 AD Object: Value = 75.000, Derivative: d(x)= 20.000 ; d(y)= 10.000 ;
 AD Object: Value = 108.000, Derivative: d(x)= 24.000 ; d(y)= 12.000 ;
 AD Object: Value = 147.000, Derivative: d(x)= 28.000 ; d(y)= 14.000 ;
 AD Object: Value = 192.000, Derivative: d(x)= 32.000 ; d(y)= 16.000 ;
 AD Object: Value = 243.000, Derivative: d(x)= 36.000 ; d(y)= 18.000 ; ]
[  3.  12.  27.  48.  75. 108. 147. 192. 243.]
[ 4.  8. 12. 16. 20. 24. 28. 32. 36.]
[ 2.  4.  6.  8. 10. 12. 14. 16. 18.]


In [16]:
x = ad.AD_Object(2, 'x')
y= ad.sigmoid(x)
print(y)

AD Object: Value = 0.881, Derivative: d(x)= 0.105 ; 
